### ISSUE TITLE
OSError: Can't load tokenizer for openai/clip-vit-large-patch

### ISSUE THREAD

**Issue by dza6549** [rupeshs/SDImageGenerator#1]
Hi there

Thank you for making this. Very clean installation. I get this error when trying to Dream. Can you please advise? Error not recorded in logs.

Thank you

![error](https://user-images.githubusercontent.com/27390320/194126912-a2f75dcc-fcf9-4731-8daa-a223fe61edd4.PNG)

**Comment by gitsd1** [comment]
Same here

`"OSError: Can't load tokenizer for 'openai/clip-vit-large-patch14'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'openai/clip-vit-large-patch14' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer."`

+ full log file
[SdImageGenerator_logs.txt](https://github.com/rupeshs/SDImageGenerator/files/9718985/SdImageGenerator_logs.txt)

**Comment by rupeshs** [comment]
This issue has been fixed,please download SDImageGenerator v1.0.5
https://rupeshsreeraman.itch.io/sdimagegenerator

**Comment by gitsd1** [comment]
Thank you!

**Comment by dza6549** [comment]
Thank you, that fixed the issue
